# Generated by Django 4.2.27 on 2026-01-21 06:10

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='手机号')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='头像')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Poetry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('author', models.CharField(blank=True, max_length=50, null=True, verbose_name='作者')),
                ('poetry_type', models.CharField(choices=[('shijing', '诗经'), ('chuci', '楚辞')], max_length=20, verbose_name='类型')),
                ('section', models.CharField(blank=True, max_length=50, null=True, verbose_name='章节')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '诗词',
                'verbose_name_plural': '诗词',
                'ordering': ['poetry_type', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Surname',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True, verbose_name='姓氏')),
                ('pinyin', models.CharField(blank=True, max_length=50, null=True, verbose_name='拼音')),
                ('origin', models.TextField(blank=True, null=True, verbose_name='来源')),
                ('meaning', models.TextField(blank=True, null=True, verbose_name='含义')),
                ('frequency', models.IntegerField(default=0, verbose_name='使用频率')),
            ],
            options={
                'verbose_name': '姓氏',
                'verbose_name_plural': '姓氏',
                'ordering': ['-frequency', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.CharField(max_length=5, unique=True, verbose_name='汉字')),
                ('pinyin', models.CharField(max_length=20, verbose_name='拼音')),
                ('meaning', models.TextField(verbose_name='含义')),
                ('gender_preference', models.CharField(choices=[('male', '男性'), ('female', '女性'), ('neutral', '中性')], default='neutral', max_length=10, verbose_name='性别倾向')),
                ('tone', models.CharField(choices=[('ping', '平声'), ('ze', '仄声'), ('unknown', '未知')], default='unknown', max_length=10, verbose_name='声调')),
                ('frequency', models.IntegerField(default=0, verbose_name='出现频率')),
                ('tags', models.JSONField(default=list, verbose_name='标签')),
                ('from_poetry', models.ManyToManyField(related_name='words', to='gen_names.poetry', verbose_name='来源诗词')),
            ],
            options={
                'verbose_name': '字词',
                'verbose_name_plural': '字词',
                'ordering': ['-frequency', 'character'],
            },
        ),
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('given_name', models.CharField(max_length=20, verbose_name='名字')),
                ('full_name', models.CharField(max_length=50, verbose_name='全名')),
                ('gender', models.CharField(choices=[('M', '男'), ('F', '女')], max_length=1, verbose_name='性别')),
                ('pinyin', models.CharField(blank=True, max_length=100, null=True, verbose_name='拼音')),
                ('meaning', models.TextField(verbose_name='含义')),
                ('origin', models.TextField(verbose_name='词源')),
                ('tags', models.JSONField(default=list, verbose_name='标签')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='是否收藏')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_names', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('reference_poetry', models.ManyToManyField(related_name='generated_names', to='gen_names.poetry', verbose_name='参考诗词')),
                ('surname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='names', to='gen_names.surname', verbose_name='姓氏')),
            ],
            options={
                'verbose_name': '名字',
                'verbose_name_plural': '名字',
                'ordering': ['-created_at'],
                'unique_together': {('full_name', 'created_by')},
            },
        ),
        migrations.CreateModel(
            name='UserFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='gen_names.name', verbose_name='收藏的名字')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户收藏',
                'verbose_name_plural': '用户收藏',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'name')},
            },
        ),
    ]
