# Generated by Django 4.2.27 on 2026-01-21 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gen_names', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reset_token',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='密码重置令牌'),
        ),
    ]
