# Generated by Django 4.2.27 on 2026-01-21 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gen_names', '0002_user_reset_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='wuxing',
            field=models.CharField(choices=[('jin', '金'), ('mu', '木'), ('shui', '水'), ('huo', '火'), ('tu', '土'), ('unknown', '未知')], default='unknown', max_length=10, verbose_name='五行属性'),
        ),
    ]
