# Generated by Django 4.2.27 on 2026-01-21 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gen_names', '0003_word_wuxing'),
    ]

    operations = [
        migrations.AddField(
            model_name='name',
            name='bagua_suggestions',
            field=models.JSONField(default=dict, verbose_name='八卦建议'),
        ),
        migrations.AddField(
            model_name='name',
            name='name_score',
            field=models.JSONField(default=dict, verbose_name='名字评分'),
        ),
        migrations.AddField(
            model_name='name',
            name='wuxing_analysis',
            field=models.JSONField(default=dict, verbose_name='五行分析'),
        ),
    ]
