# Generated by Django 4.2.27 on 2026-01-21 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gen_names', '0004_name_bagua_suggestions_name_name_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='name',
            name='phonology_analysis',
            field=models.JSONField(default=dict, verbose_name='音韵分析'),
        ),
    ]
