# Generated by Django 4.2.27 on 2026-01-21 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gen_names', '0005_name_phonology_analysis'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='userfavorite',
            index=models.Index(fields=['user', '-created_at'], name='gen_names_u_user_id_2316fa_idx'),
        ),
        migrations.AddIndex(
            model_name='userfavorite',
            index=models.Index(fields=['-created_at'], name='gen_names_u_created_d2f1ec_idx'),
        ),
        migrations.AddIndex(
            model_name='word',
            index=models.Index(fields=['frequency'], name='gen_names_w_frequen_e8bbc1_idx'),
        ),
        migrations.AddIndex(
            model_name='word',
            index=models.Index(fields=['wuxing'], name='gen_names_w_wuxing_63a322_idx'),
        ),
        migrations.AddIndex(
            model_name='word',
            index=models.Index(fields=['gender_preference'], name='gen_names_w_gender__4e3a93_idx'),
        ),
    ]
