# Generated by Django 4.2.27 on 2026-01-23 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gen_names', '0006_userfavorite_gen_names_u_user_id_2316fa_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='name',
            name='birth_month',
            field=models.IntegerField(blank=True, null=True, verbose_name='出生月份'),
        ),
        migrations.AddField(
            model_name='name',
            name='is_lunar_month',
            field=models.BooleanField(default=True, verbose_name='是否农历月份'),
        ),
        migrations.AddField(
            model_name='name',
            name='shengxiao',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='生肖'),
        ),
        migrations.AddField(
            model_name='name',
            name='shichen',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='时辰'),
        ),
        migrations.AddField(
            model_name='name',
            name='traditional_analysis',
            field=models.JSONField(default=dict, verbose_name='传统元素分析'),
        ),
    ]
